### ISSUE TITLE
load_temporal_dataset() got an unexpected keyword argument 'exclude_similar_sentences'

### ISSUE THREAD

**Issue by carschno** [guyrosin/tempobert#2]
I have been trying to apply the TempoBert model on my own data. For my understanding, I have tried to run the existing test scripts. However, `sentence_time_prediction.py` runs into this issue:

```console
$ python sentence_time_prediction.py 
2023-04-20 13:43:44.825 | INFO     | __main__:<module>:116 - Will evaluate: ''
2023-04-20 13:43:44.825 | INFO     | data_utils:split_temporal_dataset_files:133 - Loading dataset files...
Traceback (most recent call last):
  File "./tempobert/sentence_time_prediction.py", line 119, in <module>
    sentence_time_prediction(
  File "./tempobert/sentence_time_prediction.py", line 43, in sentence_time_prediction
    _, test_dataset = data_utils.split_temporal_dataset_files(
  File "./tempobert/data_utils.py", line 140, in split_temporal_dataset_files
    dataset = load_temporal_dataset(
TypeError: load_temporal_dataset() got an unexpected keyword argument 'exclude_similar_sentences'
```

**Comment by guyrosin** [comment]
Hi @carschno,
Thanks for reporting this! I've just pushed a fix by removing this obsolete argument.
